# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\desktop\ros2qt\src\qt_gui\resource\ui\valve_ui_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1180, 780))
        MainWindow.setStyleSheet("\n"
"QMainWindow, QWidget#centralwidget{\n"
"    background-color:#eef5fb;\n"
"    font-family:\"Microsoft YaHei\", \"Segoe UI\", Arial;\n"
"    color:#102a43;\n"
"}\n"
"QFrame#headerFrame{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0b2d57, stop:0.55 #0f5f9f, stop:1 #1e88d1);\n"
"    border-radius:14px;\n"
"}\n"
"QLabel#logoLabel{\n"
"    background-color:rgba(255,255,255,38);\n"
"    border:1px solid rgba(255,255,255,80);\n"
"    border-radius:18px;\n"
"    color:white;\n"
"    font-size:26px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#titleLabel{\n"
"    color:white;\n"
"    font-size:30px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#subtitleLabel{\n"
"    color:#d9ecff;\n"
"    font-size:15px;\n"
"}\n"
"QLabel#systemStatusLabel{\n"
"    color:white;\n"
"    background-color:rgba(255,255,255,35);\n"
"    border:1px solid rgba(255,255,255,75);\n"
"    border-radius:12px;\n"
"    padding:10px 18px;\n"
"    font-size:17px;\n"
"    font-weight:700;\n"
"}\n"
"QFrame.card{\n"
"    background-color:#ffffff;\n"
"    border:1px solid #d7e6f5;\n"
"    border-radius:14px;\n"
"}\n"
"QFrame#cameraPanel, QFrame#rightPanel{\n"
"    background-color:#ffffff;\n"
"    border:1px solid #d5e7f8;\n"
"    border-radius:16px;\n"
"}\n"
"QLabel.sectionTitle{\n"
"    color:#0c3b6e;\n"
"    font-size:20px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel.hintLabel{\n"
"    color:#6b7c93;\n"
"    font-size:13px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    border-radius:9px;\n"
"    padding:9px 18px;\n"
"    font-size:15px;\n"
"    font-weight:600;\n"
"    color:white;\n"
"    background-color:#2f80c7;\n"
"}\n"
"QPushButton:hover{ background-color:#1f6fb8; }\n"
"QPushButton:pressed{ background-color:#155a96; }\n"
"QPushButton#stopCameraButton{\n"
"    background-color:#52687d;\n"
"}\n"
"QPushButton#stopCameraButton:hover{ background-color:#44576b; }\n"
"QPushButton#connectArmButton{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #26a8e8, stop:1 #1c55e8);\n"
"    min-height:28px;\n"
"}\n"
"QPushButton#rotateValveButton{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #1fb6ff, stop:1 #6c3cff);\n"
"    border-radius:14px;\n"
"    min-height:54px;\n"
"    font-size:22px;\n"
"    font-weight:800;\n"
"}\n"
"QComboBox{\n"
"    background-color:#ffffff;\n"
"    border:1px solid #bfd6ee;\n"
"    border-radius:8px;\n"
"    padding:7px 12px;\n"
"    font-size:15px;\n"
"    min-height:24px;\n"
"}\n"
"QLineEdit, QLabel.valueBox, QLabel.commandBox{\n"
"    background-color:#f6faff;\n"
"    border:1px solid #c9dff3;\n"
"    border-radius:8px;\n"
"    padding:8px 12px;\n"
"    font-size:15px;\n"
"}\n"
"QLabel.valueBox{\n"
"    color:#0f2742;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#cameraViewLabel{\n"
"    background-color:#07111d;\n"
"    color:#eaf5ff;\n"
"    border:2px solid #143b63;\n"
"    border-radius:14px;\n"
"    font-size:25px;\n"
"    font-weight:700;\n"
"}\n"
"QFrame.statusCard{\n"
"    background-color:#fbfdff;\n"
"    border:1px solid #d4e6f8;\n"
"    border-radius:18px;\n"
"}\n"
"QLabel.statusIcon{\n"
"    background-color:#eaf4ff;\n"
"    border:1px solid #cde5ff;\n"
"    border-radius:20px;\n"
"    color:#1f74d1;\n"
"    font-size:22px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel.statusMain{\n"
"    color:#073b72;\n"
"    font-size:22px;\n"
"    font-weight:800;\n"
"}\n"
"QLabel.statusSub{\n"
"    color:#708399;\n"
"    font-size:12px;\n"
"}\n"
"QTextEdit#commandLogEdit{\n"
"    background-color:#f7fbff;\n"
"    border:1px solid #cfe2f5;\n"
"    border-radius:10px;\n"
"    color:#5d7188;\n"
"    font-size:14px;\n"
"    padding:8px;\n"
"}\n"
"QLabel.fieldLabel{\n"
"    color:#15395f;\n"
"    font-size:15px;\n"
"    font-weight:650;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setContentsMargins(22, 18, 22, 18)
        self.mainVerticalLayout.setSpacing(16)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 106))
        self.headerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerFrame.setObjectName("headerFrame")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.headerLayout.setContentsMargins(26, 16, 26, 16)
        self.headerLayout.setSpacing(16)
        self.headerLayout.setObjectName("headerLayout")
        self.logoLabel = QtWidgets.QLabel(self.headerFrame)
        self.logoLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.logoLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.headerLayout.addWidget(self.logoLabel)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setSpacing(6)
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.headerFrame)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.headerFrame)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.systemStatusLabel = QtWidgets.QLabel(self.headerFrame)
        self.systemStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.systemStatusLabel.setObjectName("systemStatusLabel")
        self.headerLayout.addWidget(self.systemStatusLabel)
        self.mainVerticalLayout.addWidget(self.headerFrame)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(16)
        self.contentLayout.setObjectName("contentLayout")
        self.cameraPanel = QtWidgets.QFrame(self.centralwidget)
        self.cameraPanel.setObjectName("cameraPanel")
        self.cameraPanelLayout = QtWidgets.QVBoxLayout(self.cameraPanel)
        self.cameraPanelLayout.setContentsMargins(18, 18, 18, 18)
        self.cameraPanelLayout.setSpacing(14)
        self.cameraPanelLayout.setObjectName("cameraPanelLayout")
        self.cameraToolbarCard = QtWidgets.QFrame(self.cameraPanel)
        self.cameraToolbarCard.setObjectName("cameraToolbarCard")
        self.cameraToolbarLayout = QtWidgets.QHBoxLayout(self.cameraToolbarCard)
        self.cameraToolbarLayout.setContentsMargins(16, 12, 16, 12)
        self.cameraToolbarLayout.setSpacing(12)
        self.cameraToolbarLayout.setObjectName("cameraToolbarLayout")
        self.cameraTitleLayout = QtWidgets.QVBoxLayout()
        self.cameraTitleLayout.setObjectName("cameraTitleLayout")
        self.cameraTitleLabel = QtWidgets.QLabel(self.cameraToolbarCard)
        self.cameraTitleLabel.setObjectName("cameraTitleLabel")
        self.cameraTitleLayout.addWidget(self.cameraTitleLabel)
        self.cameraHintLabel = QtWidgets.QLabel(self.cameraToolbarCard)
        self.cameraHintLabel.setObjectName("cameraHintLabel")
        self.cameraTitleLayout.addWidget(self.cameraHintLabel)
        self.cameraToolbarLayout.addLayout(self.cameraTitleLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cameraToolbarLayout.addItem(spacerItem1)
        self.imageModeComboBox = QtWidgets.QComboBox(self.cameraToolbarCard)
        self.imageModeComboBox.setObjectName("imageModeComboBox")
        self.imageModeComboBox.addItem("")
        self.imageModeComboBox.addItem("")
        self.cameraToolbarLayout.addWidget(self.imageModeComboBox)
        self.startCameraButton = QtWidgets.QPushButton(self.cameraToolbarCard)
        self.startCameraButton.setObjectName("startCameraButton")
        self.cameraToolbarLayout.addWidget(self.startCameraButton)
        self.stopCameraButton = QtWidgets.QPushButton(self.cameraToolbarCard)
        self.stopCameraButton.setObjectName("stopCameraButton")
        self.cameraToolbarLayout.addWidget(self.stopCameraButton)
        self.cameraPanelLayout.addWidget(self.cameraToolbarCard)
        self.cameraViewLabel = QtWidgets.QLabel(self.cameraPanel)
        self.cameraViewLabel.setMinimumSize(QtCore.QSize(720, 430))
        self.cameraViewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraViewLabel.setObjectName("cameraViewLabel")
        self.cameraPanelLayout.addWidget(self.cameraViewLabel)
        self.statusCardsLayout = QtWidgets.QHBoxLayout()
        self.statusCardsLayout.setSpacing(14)
        self.statusCardsLayout.setObjectName("statusCardsLayout")
        self.fpsCard = QtWidgets.QFrame(self.cameraPanel)
        self.fpsCard.setObjectName("fpsCard")
        self.fpsLayout = QtWidgets.QHBoxLayout(self.fpsCard)
        self.fpsLayout.setContentsMargins(16, 12, 16, 12)
        self.fpsLayout.setObjectName("fpsLayout")
        self.fpsIcon = QtWidgets.QLabel(self.fpsCard)
        self.fpsIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.fpsIcon.setMaximumSize(QtCore.QSize(48, 48))
        self.fpsIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.fpsIcon.setObjectName("fpsIcon")
        self.fpsLayout.addWidget(self.fpsIcon)
        self.fpsTextLayout = QtWidgets.QVBoxLayout()
        self.fpsTextLayout.setObjectName("fpsTextLayout")
        self.fpsValueLabel = QtWidgets.QLabel(self.fpsCard)
        self.fpsValueLabel.setObjectName("fpsValueLabel")
        self.fpsTextLayout.addWidget(self.fpsValueLabel)
        self.fpsDescLabel = QtWidgets.QLabel(self.fpsCard)
        self.fpsDescLabel.setObjectName("fpsDescLabel")
        self.fpsTextLayout.addWidget(self.fpsDescLabel)
        self.fpsLayout.addLayout(self.fpsTextLayout)
        self.statusCardsLayout.addWidget(self.fpsCard)
        self.modelCard = QtWidgets.QFrame(self.cameraPanel)
        self.modelCard.setObjectName("modelCard")
        self.modelLayout = QtWidgets.QHBoxLayout(self.modelCard)
        self.modelLayout.setContentsMargins(16, 12, 16, 12)
        self.modelLayout.setObjectName("modelLayout")
        self.modelIcon = QtWidgets.QLabel(self.modelCard)
        self.modelIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.modelIcon.setMaximumSize(QtCore.QSize(48, 48))
        self.modelIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.modelIcon.setObjectName("modelIcon")
        self.modelLayout.addWidget(self.modelIcon)
        self.modelTextLayout = QtWidgets.QVBoxLayout()
        self.modelTextLayout.setObjectName("modelTextLayout")
        self.modelValueLabel = QtWidgets.QLabel(self.modelCard)
        self.modelValueLabel.setObjectName("modelValueLabel")
        self.modelTextLayout.addWidget(self.modelValueLabel)
        self.modelDescLabel = QtWidgets.QLabel(self.modelCard)
        self.modelDescLabel.setObjectName("modelDescLabel")
        self.modelTextLayout.addWidget(self.modelDescLabel)
        self.modelLayout.addLayout(self.modelTextLayout)
        self.statusCardsLayout.addWidget(self.modelCard)
        self.cameraStatusCard = QtWidgets.QFrame(self.cameraPanel)
        self.cameraStatusCard.setObjectName("cameraStatusCard")
        self.cameraStatusLayout = QtWidgets.QHBoxLayout(self.cameraStatusCard)
        self.cameraStatusLayout.setContentsMargins(16, 12, 16, 12)
        self.cameraStatusLayout.setObjectName("cameraStatusLayout")
        self.cameraStatusIcon = QtWidgets.QLabel(self.cameraStatusCard)
        self.cameraStatusIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.cameraStatusIcon.setMaximumSize(QtCore.QSize(48, 48))
        self.cameraStatusIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraStatusIcon.setObjectName("cameraStatusIcon")
        self.cameraStatusLayout.addWidget(self.cameraStatusIcon)
        self.cameraStatusTextLayout = QtWidgets.QVBoxLayout()
        self.cameraStatusTextLayout.setObjectName("cameraStatusTextLayout")
        self.cameraStatusValueLabel = QtWidgets.QLabel(self.cameraStatusCard)
        self.cameraStatusValueLabel.setObjectName("cameraStatusValueLabel")
        self.cameraStatusTextLayout.addWidget(self.cameraStatusValueLabel)
        self.cameraStatusDescLabel = QtWidgets.QLabel(self.cameraStatusCard)
        self.cameraStatusDescLabel.setObjectName("cameraStatusDescLabel")
        self.cameraStatusTextLayout.addWidget(self.cameraStatusDescLabel)
        self.cameraStatusLayout.addLayout(self.cameraStatusTextLayout)
        self.statusCardsLayout.addWidget(self.cameraStatusCard)
        self.cameraPanelLayout.addLayout(self.statusCardsLayout)
        self.rotateValveButton = QtWidgets.QPushButton(self.cameraPanel)
        self.rotateValveButton.setObjectName("rotateValveButton")
        self.cameraPanelLayout.addWidget(self.rotateValveButton)
        self.contentLayout.addWidget(self.cameraPanel)
        self.rightPanel = QtWidgets.QFrame(self.centralwidget)
        self.rightPanel.setMinimumSize(QtCore.QSize(445, 0))
        self.rightPanel.setMaximumSize(QtCore.QSize(520, 16777215))
        self.rightPanel.setObjectName("rightPanel")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setContentsMargins(16, 18, 16, 18)
        self.rightLayout.setSpacing(14)
        self.rightLayout.setObjectName("rightLayout")
        self.armConnectCard = QtWidgets.QFrame(self.rightPanel)
        self.armConnectCard.setObjectName("armConnectCard")
        self.armConnectLayout = QtWidgets.QVBoxLayout(self.armConnectCard)
        self.armConnectLayout.setContentsMargins(16, 14, 16, 14)
        self.armConnectLayout.setSpacing(10)
        self.armConnectLayout.setObjectName("armConnectLayout")
        self.armTitleLabel = QtWidgets.QLabel(self.armConnectCard)
        self.armTitleLabel.setObjectName("armTitleLabel")
        self.armConnectLayout.addWidget(self.armTitleLabel)
        self.armFormLayout = QtWidgets.QFormLayout()
        self.armFormLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.armFormLayout.setHorizontalSpacing(14)
        self.armFormLayout.setVerticalSpacing(9)
        self.armFormLayout.setObjectName("armFormLayout")
        self.ipLabel = QtWidgets.QLabel(self.armConnectCard)
        self.ipLabel.setObjectName("ipLabel")
        self.armFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ipLabel)
        self.armIpLineEdit = QtWidgets.QLineEdit(self.armConnectCard)
        self.armIpLineEdit.setObjectName("armIpLineEdit")
        self.armFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.armIpLineEdit)
        self.portLabel = QtWidgets.QLabel(self.armConnectCard)
        self.portLabel.setObjectName("portLabel")
        self.armFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.armPortLineEdit = QtWidgets.QLineEdit(self.armConnectCard)
        self.armPortLineEdit.setObjectName("armPortLineEdit")
        self.armFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.armPortLineEdit)
        self.armConnectLayout.addLayout(self.armFormLayout)
        self.connectArmButton = QtWidgets.QPushButton(self.armConnectCard)
        self.connectArmButton.setObjectName("connectArmButton")
        self.armConnectLayout.addWidget(self.connectArmButton)
        self.rightLayout.addWidget(self.armConnectCard)
        self.valveDataCard = QtWidgets.QFrame(self.rightPanel)
        self.valveDataCard.setObjectName("valveDataCard")
        self.valveDataLayout = QtWidgets.QVBoxLayout(self.valveDataCard)
        self.valveDataLayout.setContentsMargins(16, 14, 16, 14)
        self.valveDataLayout.setSpacing(10)
        self.valveDataLayout.setObjectName("valveDataLayout")
        self.valveTitleLabel = QtWidgets.QLabel(self.valveDataCard)
        self.valveTitleLabel.setObjectName("valveTitleLabel")
        self.valveDataLayout.addWidget(self.valveTitleLabel)
        self.valveFormLayout = QtWidgets.QFormLayout()
        self.valveFormLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valveFormLayout.setHorizontalSpacing(14)
        self.valveFormLayout.setVerticalSpacing(10)
        self.valveFormLayout.setObjectName("valveFormLayout")
        self.xLabel = QtWidgets.QLabel(self.valveDataCard)
        self.xLabel.setObjectName("xLabel")
        self.valveFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.xLabel)
        self.xValueLabel = QtWidgets.QLabel(self.valveDataCard)
        self.xValueLabel.setText("")
        self.xValueLabel.setObjectName("xValueLabel")
        self.valveFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xValueLabel)
        self.yLabel = QtWidgets.QLabel(self.valveDataCard)
        self.yLabel.setObjectName("yLabel")
        self.valveFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.yLabel)
        self.yValueLabel = QtWidgets.QLabel(self.valveDataCard)
        self.yValueLabel.setText("")
        self.yValueLabel.setObjectName("yValueLabel")
        self.valveFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yValueLabel)
        self.zLabel = QtWidgets.QLabel(self.valveDataCard)
        self.zLabel.setObjectName("zLabel")
        self.valveFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.zLabel)
        self.zValueLabel = QtWidgets.QLabel(self.valveDataCard)
        self.zValueLabel.setText("")
        self.zValueLabel.setObjectName("zValueLabel")
        self.valveFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zValueLabel)
        self.confLabel = QtWidgets.QLabel(self.valveDataCard)
        self.confLabel.setObjectName("confLabel")
        self.valveFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.confLabel)
        self.confidenceValueLabel = QtWidgets.QLabel(self.valveDataCard)
        self.confidenceValueLabel.setText("")
        self.confidenceValueLabel.setObjectName("confidenceValueLabel")
        self.valveFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.confidenceValueLabel)
        self.valveDataLayout.addLayout(self.valveFormLayout)
        self.rightLayout.addWidget(self.valveDataCard)
        self.commandCard = QtWidgets.QFrame(self.rightPanel)
        self.commandCard.setObjectName("commandCard")
        self.commandLayout = QtWidgets.QVBoxLayout(self.commandCard)
        self.commandLayout.setContentsMargins(16, 14, 16, 14)
        self.commandLayout.setSpacing(10)
        self.commandLayout.setObjectName("commandLayout")
        self.commandTitleLabel = QtWidgets.QLabel(self.commandCard)
        self.commandTitleLabel.setObjectName("commandTitleLabel")
        self.commandLayout.addWidget(self.commandTitleLabel)
        self.currentCommandLabel = QtWidgets.QLabel(self.commandCard)
        self.currentCommandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentCommandLabel.setObjectName("currentCommandLabel")
        self.commandLayout.addWidget(self.currentCommandLabel)
        self.commandLogEdit = QtWidgets.QTextEdit(self.commandCard)
        self.commandLogEdit.setObjectName("commandLogEdit")
        self.commandLayout.addWidget(self.commandLogEdit)
        self.rightLayout.addWidget(self.commandCard)
        self.contentLayout.addWidget(self.rightPanel)
        self.mainVerticalLayout.addLayout(self.contentLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intelligent Valve Operation System"))
        self.logoLabel.setText(_translate("MainWindow", "AI"))
        self.titleLabel.setText(_translate("MainWindow", "机械臂阀门识别与定位控制系统"))
        self.subtitleLabel.setText(_translate("MainWindow", "RGB-D Vision · Valve Localization · Robotic Arm Command Monitoring"))
        self.systemStatusLabel.setText(_translate("MainWindow", "● 系统状态：待连接"))
        self.cameraToolbarCard.setProperty("class", _translate("MainWindow", "card"))
        self.cameraTitleLabel.setText(_translate("MainWindow", "图像显示区域"))
        self.cameraTitleLabel.setProperty("class", _translate("MainWindow", "sectionTitle"))
        self.cameraHintLabel.setText(_translate("MainWindow", "支持 RGB 图像与深度图切换显示"))
        self.cameraHintLabel.setProperty("class", _translate("MainWindow", "hintLabel"))
        self.imageModeComboBox.setItemText(0, _translate("MainWindow", "RGB 图像"))
        self.imageModeComboBox.setItemText(1, _translate("MainWindow", "深度图"))
        self.startCameraButton.setText(_translate("MainWindow", "启动相机"))
        self.stopCameraButton.setText(_translate("MainWindow", "停止相机"))
        self.cameraViewLabel.setText(_translate("MainWindow", "◎\\nRGB Camera View"))
        self.fpsCard.setProperty("class", _translate("MainWindow", "statusCard"))
        self.fpsIcon.setText(_translate("MainWindow", "▣"))
        self.fpsIcon.setProperty("class", _translate("MainWindow", "statusIcon"))
        self.fpsValueLabel.setText(_translate("MainWindow", "-- FPS"))
        self.fpsValueLabel.setProperty("class", _translate("MainWindow", "statusMain"))
        self.fpsDescLabel.setText(_translate("MainWindow", "相机帧率"))
        self.fpsDescLabel.setProperty("class", _translate("MainWindow", "statusSub"))
        self.modelCard.setProperty("class", _translate("MainWindow", "statusCard"))
        self.modelIcon.setText(_translate("MainWindow", "◇"))
        self.modelIcon.setProperty("class", _translate("MainWindow", "statusIcon"))
        self.modelValueLabel.setText(_translate("MainWindow", "YOLO11"))
        self.modelValueLabel.setProperty("class", _translate("MainWindow", "statusMain"))
        self.modelDescLabel.setText(_translate("MainWindow", "识别模型"))
        self.modelDescLabel.setProperty("class", _translate("MainWindow", "statusSub"))
        self.cameraStatusCard.setProperty("class", _translate("MainWindow", "statusCard"))
        self.cameraStatusIcon.setText(_translate("MainWindow", "●"))
        self.cameraStatusIcon.setProperty("class", _translate("MainWindow", "statusIcon"))
        self.cameraStatusValueLabel.setText(_translate("MainWindow", "未启动"))
        self.cameraStatusValueLabel.setProperty("class", _translate("MainWindow", "statusMain"))
        self.cameraStatusDescLabel.setText(_translate("MainWindow", "相机状态"))
        self.cameraStatusDescLabel.setProperty("class", _translate("MainWindow", "statusSub"))
        self.rotateValveButton.setText(_translate("MainWindow", "一键旋阀"))
        self.armConnectCard.setProperty("class", _translate("MainWindow", "card"))
        self.armTitleLabel.setText(_translate("MainWindow", "机械臂连接信息"))
        self.armTitleLabel.setProperty("class", _translate("MainWindow", "sectionTitle"))
        self.ipLabel.setText(_translate("MainWindow", "机械臂 IP："))
        self.ipLabel.setProperty("class", _translate("MainWindow", "fieldLabel"))
        self.armIpLineEdit.setText(_translate("MainWindow", "192.168.0.200"))
        self.portLabel.setText(_translate("MainWindow", "端口："))
        self.portLabel.setProperty("class", _translate("MainWindow", "fieldLabel"))
        self.armPortLineEdit.setText(_translate("MainWindow", "2090"))
        self.connectArmButton.setText(_translate("MainWindow", "连接机械臂"))
        self.valveDataCard.setProperty("class", _translate("MainWindow", "card"))
        self.valveTitleLabel.setText(_translate("MainWindow", "阀门位置数据"))
        self.valveTitleLabel.setProperty("class", _translate("MainWindow", "sectionTitle"))
        self.xLabel.setText(_translate("MainWindow", "X 坐标："))
        self.xLabel.setProperty("class", _translate("MainWindow", "fieldLabel"))
        self.xValueLabel.setProperty("class", _translate("MainWindow", "valueBox"))
        self.yLabel.setText(_translate("MainWindow", "Y 坐标："))
        self.yLabel.setProperty("class", _translate("MainWindow", "fieldLabel"))
        self.yValueLabel.setProperty("class", _translate("MainWindow", "valueBox"))
        self.zLabel.setText(_translate("MainWindow", "Z 深度："))
        self.zLabel.setProperty("class", _translate("MainWindow", "fieldLabel"))
        self.zValueLabel.setProperty("class", _translate("MainWindow", "valueBox"))
        self.confLabel.setText(_translate("MainWindow", "识别置信度："))
        self.confLabel.setProperty("class", _translate("MainWindow", "fieldLabel"))
        self.confidenceValueLabel.setProperty("class", _translate("MainWindow", "valueBox"))
        self.commandCard.setProperty("class", _translate("MainWindow", "card"))
        self.commandTitleLabel.setText(_translate("MainWindow", "当前执行命令"))
        self.commandTitleLabel.setProperty("class", _translate("MainWindow", "sectionTitle"))
        self.currentCommandLabel.setText(_translate("MainWindow", "暂无执行命令"))
        self.currentCommandLabel.setProperty("class", _translate("MainWindow", "commandBox"))
        self.commandLogEdit.setPlaceholderText(_translate("MainWindow", "机械臂指令日志将在此显示..."))
